### ISSUE TITLE
Decrypting Backup not work

### ISSUE THREAD

**Issue by opalhair** [shivpatel/bitwarden_rs_dropbox_backup#1]
unknown option '-pbkdf2'
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by fefz** [comment]
> unknown option '-pbkdf2'
> gzip: stdin: unexpected end of file
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now

same, have you fixed it ?

**Comment by shivpatel** [comment]
The error may be related to the version of `openssl` installed on the host you are attempting to decrypt on. Have you tried running the Docker image in interactive mode, volume mounting your backup file, and trying to decrypt in the container? That is how I have recovered backups in the past with no issues.

Update. The version of OpenSSL installed on the pre-built Docker images is:
`OpenSSL 1.1.1d  10 Sep 2019 (Library: OpenSSL 1.1.1c  28 May 2019)`

**Comment by fefz** [comment]
> The error may be related to the version of `openssl` installed on the host you are attempting to decrypt on. Have you tried running the Docker image in interactive mode, volume mounting your backup file, and trying to decrypt in the container? That is how I have recovered backups in the past with no issues.
> 
> Update. The version of OpenSSL installed on the pre-built Docker images is:
> `OpenSSL 1.1.1d 10 Sep 2019 (Library: OpenSSL 1.1.1c 28 May 2019)`

solved
