### ISSUE TITLE
Missing attachments and /config folder should be defaulted to ./config instead than /config

### ISSUE THREAD

**Issue by Johan3F** [shivpatel/bitwarden_rs_dropbox_backup#3]
I've been willing to use this image. However, I think it would make sense to backup the attachments folder as well, not only the DB. 
Also, the `docker-compose.yml` default the configuration folder to `/config`. I think it would make more sense to defaulted to `./config`.
I hope it makes sense.
I've forked the repo and made the following changes:
- Instead of just mounting the DB file, it mounts the bwdata folder
- Uses both the DB and the attachments folder to create the encrypted backup file
- Changes the default configuration folder to have the `./config` instead of `/config`
It would be great if we could merge this, so we could still have one unified backup tool to dropbox. Let me know your thoughts about this.

**Comment by shivpatel** [comment]
@Johan3F both valid points. I think the config path was a typo that got through on the last PR.

I'm down to merge your changes in. Can you open a PR please?

**Comment by Johan3F** [comment]
Opened :+1:
