### ISSUE TITLE
change timezone

### ISSUE THREAD

**Issue by yfhyou** [shivpatel/bitwarden_rs_dropbox_backup#8]
Any way to change the container timezone?
I've tried setting an env variable `TZ=` to my local time as well as mounting `/etc/localtime:/etc/localtime:ro` as a volume. The container still seems to use UTC time when tagging backups.
Not a big deal, but seems like maybe I am missing something simple.

**Comment by shivpatel** [comment]
@youngt2 Looks like we're missing the `tzdata` package for timezones to work correctly.

See: https://github.com/alpinelinux/docker-alpine/issues/44#issuecomment-537896546

If you'd like to fork and PR, I am happy to merge in the changes.

**Comment by shivpatel** [comment]
Changes merged into `master`
